SELECT M.fID,Web,Trim,Linedepth,user_fID,AuditFields_InsertDate,AuditFields_UpdateDate,LineType_fID,Finished,PaperMass_fID,PaperMassFlute_fID,Remark,D.ORDERSN,CUSTOM_FID,SEC,STKMODEL_FID,LENGTH,WIDTH,STK,QTY,STK_NUMBER,[LEVEL],ISNORMAL,LINES,CUST_ORDERID,WASTQTY FROM ORDERS M,ORDERITEMS D WHERE D.ORDER_FID = M.FID






